config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'books#index'

  resources :books do
    resources :comments
  end

  get "like", to: "books#like"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :likes

  validates :title, presence: true,length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 10 }
  validates :writer, presence: true, length: { minimum: 2 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  validates :commenter, presence: true, length: {minimum: 2}
  validates :body, presence: true, length: {minimum: 2}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "123456", except: [:index, :show]

  def index
    @books =Book.all
  end
  def show
    @book = Book.find params[:id]
  end
  def new
    @book = Book.new
  end
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      render :new
    end
  end
  def edit
    @book =Book.find params[:id]
  end
  def update
    @book=Book.find params[:id]
    if @book.update(book_params)
      redirect_to @book
    else
      render :edit
    end
  end
  def destroy
    @book=Book.find params[:id]
    @book.destroy

    redirect_to root_path
  end
  def like
    @book = Book.find params[:id]
    if @book.likes.where(user_id: current_user.id).present?
      like = @book.likes.where(user_id: current_user.id).first
      like.destroy
    else
      like = @book.likes.new
      like.user_id = current_user.id
      like.save
    end
    redirect_to @book
  end

private
  def book_params
    params.require(:book).permit(:title,:body,:writer, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "123456", only: :destroy
  def index
    @comments =Comment.all
  end
  def create
    @book = Book.find params[:book_id]
    @comment = @book.comments.create(comment_params)
    redirect_to @book
  end
  def destroy
    @book = Book.find params[:book_id]
    @comment = @book.comments.find params[:id]
    @comment.destroy
    redirect_to @book
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/books/_book_summary.html.haml
%div.mt-5
  %h2.header
    =link_to book.title, book
    %p
    =book.writer
  - if book.image.present?
    %br
    =image_tag(book.image, class: "book-summary-image")

  %div.body
    =book.body.truncate(500, separator: "...")
    - if book.body.size > 500
      =link_to "Read More", book
  %hr

app/views/books/_form.html.haml
= form_with model: @book do |form|
  %div
    = form.label :title, class:"form-label"
    %br
    = form.text_field :title, class:"form-control"
    - @book.errors.full_messages_for(:title).each do |error|
      %p= error
  %div
    = form.label :body, class:"form-label"
    %br
    = form.text_area :body, class:"form-control"
    - @book.errors.full_messages_for(:body).each do |error|
      %p= error
  %div
    = form.label :writer, class:"form-label"
    %br
    = form.text_field :writer, class:"form-control"
    - @book.errors.full_messages_for(:writer).each do |error|
      %p= error
  %div
    =form.label :image, class: 'form-label'
    %br
    =form.file_field :image, class: 'form-control'
  %div.mt-5.d-flex.justify-content-between
    = form.submit :"Create Book",class:"btn btn-outline-success"

app/views/books/edit.html.haml
%h2="Edit Book"
=render "form"
%br
=link_to "Back", @book,class:"btn btn-outline-secondary btn-sm"

app/views/books/index.html.haml
%ul
  =render partial: "book_summary",collection: @books, as: :book

app/views/books/new.html.haml
%h2= "New Book"
=render "form"
%br
=link_to "Back", root_path, class:"btn btn-outline-secondary btn-sm"

app/views/books/show.html.haml
- if current_user.present?
  %div.buttons.float-end
    =link_to "Edit",edit_book_path, class:"btn btn-outline-warning btn-sm"
    =link_to "Delete", book_path(@book), method: "delete",class:"btn btn-outline-danger btn-sm", data: {confirm: "Are you sure?"}
%h2=@book.title
%h3=@book.writer
- if @book.image.present?
  =image_tag(@book.image, class:"book-image")
%p= @book.body
%br
%p= @book.likes.count.to_s + " Likes"
- if current_user.present?
  - if @book.likes.where(user_id: current_user.id).present?
    =link_to "Unlike", like_path(id: @book.id), class: "btn btn-outline-secondary btn-sm"
  - else
    =link_to "Like", like_path(id: @book.id), class: "btn btn-outline-primary btn-sm"

%hr
=render "comments/comments"
%hr
=render "comments/form"

app/views/comments/_comments.html.haml
%h2 Comments
- @book.comments.each do |comment|
  .comment-box.d-flex
    %strong=comment.commenter.capitalize! + ":"
    %p=comment.body
    %div.tab
    - if current_user.present?
      =link_to "Delete", [comment.book, comment],method: "delete",data:{confirm:"Are you sure?"},class: "btn btn-outline-danger btn-sm"

app/views/comments/_form.html.haml
%h4 Add Comment
=form_with model: [@book, @book.comments.build] do |form|
  %div
    =form.label :commenter, class:"form-label"
    %br
    =form.text_field :commenter, class:"form-control"

  %div
    =form.label :body, class:"form-label"
    %br
    =form.text_area :body, class:"form-control",row: 5

  %div
    %br
      =form.submit :"Create Comment", Class:"btn btn-success btn-sm"
%br

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %a.navbar-brand{:href => "#"} Books
    %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarNav", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse
      %ul.navbar-nav
        %li.nav-item
          =link_to "Home", root_path, class: "nav-link"


        - if user_signed_in?
          %li.nav-item
          =link_to "New Book", new_book_path, class: "nav-link"
          %li.nav-item
            = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link'
        - else
          %li.nav-item
            = link_to 'Sign In', new_user_session_path, class: 'nav-link'
          %li.nav-item
            = link_to 'Register', new_user_registration_path, class: 'nav-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bookappp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    =render "layouts/navbar"
    .content
      %p.notice= notice
      %p.alert= alert
      = yield